app-name = "auto-repair"
name = "name"
surname = "surname"
email = "email"
created_at = "created"
updated_at = "updated"
user = "user"
users = "users"
active = "active"
signup = "sign up"
signup-success = "signup successfully"
password = "password"
register = "sign up"
already-signup = "already have an account?"
confirm-password = "confirm password"
signin = "login"
not-signup = "Not an account yet?"
