app-name = "auto-repair"
name = "nombre"
surname = "apellido"
email = "email"
created_at = "creado"
updated_at = "actualizado"
user = "usuario"
users = "usuarios"
active = "activo"
signup = "registro"
signup-success = "registro realizado correctamente"
password = "contrasena"
register = "registrar"
already-signup = "Ya tienes una cuenta?"
confirm-password = "confirmar contrasena"
signin = "login"
not-signup = "Todavía no tienes una cuenta?"
